import '../styles/globals.css'
import { Inter } from 'next/font/google'
// import { Alatsi } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })
// const alatsi = Alatsi({ subsets: ["latin"], variable: "--font-alatsi", display: "swap" });

export const metadata = {
  title: 'Zuhdi Ardi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
